### PR TITLE
updated solution for dealing with intraday tables including deduplication

### PR DESCRIPTION
**Pull request by ghost**
See https://github.com/coding-is-for-losers/ga4-bigquery-starter/pull/5#discussion_r537108050

### CODE REVIEW

**Comment by codingisforlosers** [comment]
Looks good!  I like this dedupe approach, easy to follow and build around.

**Comment by ghost** [comment]
Sorry, just found out this PR contained an error, fixed in new PR.

**Comment by codingisforlosers** [comment]
Thanks @jhnvdw, just merged that in.  

Are we sure that `table_date` allows us to take advantage of partitioning advantages as `_TABLE_SUFFIX` does (didn't see it [mentioned in the docs here](https://cloud.google.com/bigquery/docs/querying-wildcard-tables#scanning_a_range_of_tables_using_table_suffix) re wildcard selectors and partitioning).

**Comment by ghost** [comment]
I'm no expert on performance optimisation (yet :p ) but I've read some BQ documentation and I think you're right regarding the `dedup_events` model. Pushed another PR to fix that and also updated some small things on `partition by` and `cluster by`. If you or anyone could set some standard for performance optimisation in this project, would be great.

**Pull request merged**
